name: worflow-command
on: 
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
    checkout-actions:
        runs-on: ubuntu-latest
        steps:
          - name: commit info
            run: echo "Commit made by ${{ github.actor }} with commit id ${{ github.sha }} on repo ${{github.ref}}"

          - name: Show GitHub context
            run: |
              echo $GITHUB_SHA
              echo $GITHUB_REF

          - name: Before checkout
            run: ls -la

          - name: checout Repository
            uses: actions/checkout@v4

          - name: After checkout
            run: ls -la  
            
          - name: get context
            run: echo $context

          - name: find python version
            run: python --version            

          - name: Setup Python
            uses: actions/setup-python@v6.0.0
            with:
              python-version: '3.13' 
          
          - name: run a python script
            run: python app.py

          - name: find python version
            run: python --version

          