name: worflow-command
on: [push]
jobs:
    commands-job:
        runs-on: ubuntu-latest
        steps:
            - name: Debug step
              run: |
                echo "::notice::Starting build process"
                echo "::warning::Disk usage high"
                echo "::error::Build failed - missing file"
            
            - name: Check Disk Space
              run: |
                space=$(df -h / | tail -1 | awk '{print $4}')
                if [[ "$space" == "0G" ]]; then
                echo "::error::No disk space left!"
                elif [[ "$space" < "2G" ]]; then
                echo "::warning::Low disk space: $space"
                else
                echo "::notice::Disk space ok: $space"
                fi
 

            - name: View context attributes
              uses: actions/github-script@v8
              with:
                script: console.log(context)    
