name: docker-container
on: [workflow_dispatch]


jobs:
    docker-build:
        runs-on: ubuntu-latest
        container:
            image: python:3.15.0a2-trixie
        steps:
            - name: Check out python version
              run: --version