name: docker-container
on: [workflow_dispatch]


jobs:
    docker-build:
        runs-on: ubuntu-latest
        container:
            image: python:3.15.0a2-trixie
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Check out python version
              run: python3 --version
            
            - name: execute a script
              run: python3 ./app.py