name: docker-container
on: [push]


jobs:
    docker-build:
        runs-on: ubuntu-latest
        container:
            image: python:3.15.0a2-trixie
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Check out python version
              run: python3 --version
            
            - name: execute a script
              run: |
                python3 --version
                python3 ./app.py
                cat /etc/os-release

            - name: docker in steps
              uses: docker://python:3.14.0-slim-trixie
              with:
                    entrypoint: python3
                    args: ./app.py --version
