name: dyamic workflow
on: 
    workflow_dispatch:
        inputs:
            os:
                description: 'Operating System'
                required: true
                type: string
                default: 'ubuntu-latest,windows-latest'
            node:
                description: 'Node.js Version'
                required: true
                type: string
                default: '14,16,18'

jobs:
    prepare-matrix:
        runs-on: ubuntu-latest
        steps:
            - name: Run inline Python
              run: |
                    python - << 'EOF'
                    print("Hello from Python")
                    x = 10
                    print(x * 5)
                    EOF
    # build:
    #     strategy:
    #         matrix:
    #             os: [ubuntu-latest, windows-latest]
    #             node: [14, 16, 18]
    #     runs-on: ${{ matrix.os }}
    #     continue-on-error: true
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2
        
    #         - name: Set up Node.js ${{ matrix.node }}
    #           uses: actions/setup-node@v2
    #           with:
    #              node-version: ${{ matrix.node }}
    