name: check secrettoken
on: [push]
run-name: check secrettoken run

env:
    SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}

jobs:
    check-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                token: ${{ env.SECRET_TOKEN }}
