name: status check workflow
on: [push]
run-name: status check workflow run

jobs:
    jobs-1:
        runs-on: ubuntu-latest
        steps:
            - name: Run a one-line script
              run: echo "Hello, world!"

            - name: exit with error
              run: exit 1
            
            - name: sleep for 30 seconds
              run: sleep 30
            
            - name: runs only if previous job is successful
              if: success()
              run: echo "This job runs only if the previous job is successful."

            - name: runs only if previous job is filed
              if: failure()
              run: echo "This job runs only if the previous job is failed."
    
    jobs-2:
        runs-on: ubuntu-latest
        needs: jobs-1
        if: success()
        steps:
            - name: Run a one-line script
              run: echo "This job runs only if the previous job is successful."
    jobs-3:
        runs-on: ubuntu-latest
        needs: jobs-1
        if: failure()
        steps:
            - name: Run a one-line script
              run: echo "This job runs only if the previous job is failed."

    jobs-4:
        runs-on: ubuntu-latest
        needs: jobs-1
        if: cancelled()
        steps:
            - name: Run a one-line script
              run: echo "This job runs only if the previous job is cancelled."            