name: second-workflow

on:
  workflow_run:
    workflows: ["first-workflow"]
    types: [completed]

jobs:
    second-workflow:
        runs-on: ubuntu-latest
        steps:
          - name: Second Step
            run: echo "This is my second workflow triggered after first workflow"
        

